SRCS+= \
	MemcpyFunctionTest.cpp MemcpyTestParams.cpp MemcpyTest.cpp \
	StrcpyFunctionTest.cpp StrcpyTest.cpp \
	StrncpyFunctionTest.cpp StrncpyTest.cpp \
	StrcmpFunctionTest.cpp StrcmpTestParams.cpp StrcmpTest.cpp
  